<!-- 
******************************************************************
Fichero:    crear-problema.phtml
Asignatura: Trabajo Fin de Grado
Titulación: GIITI
Autor     : Marco Vidal García
Universidad de Oviedo
******************************************************************
-->
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8"/>
        <title>Crear ejercicio</title>
        <link rel="stylesheet" href="">
		<!--  Enlazado de la biblioteca JQuery -->
    	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<!-- Enlazado a mi fichero Javascript/JQuery -->
		<script type="text/javascript" src="javascript/functions_problemas.js" charset="utf-8"></script>
    </head>
    <body>
		<h4>Datos comunes del ejercicio</h4></br>
		<form method="post" id="formProblemas" action="">
			<label for="enunciadogeneral">Enunciado general: </label><br/>
			<textarea id="enunciadogeneral" name="enunciadogeneral" rows="3" cols="80">Introduce aquí el enunciado general del ejercicio...</textarea><br/>
			<label for="resumen">Resumen del ejercicio: </label><br/>
			<textarea id="resumen" name="resumen" rows="3" cols="80">Introduce aquí el resumen del ejercicio...</textarea><br/>
			<label for="tags">Tags: </label><br/>
			<input type="text" id="tags" name="tags"/><br/>
		</form>
<br/><br/>
<button id='cancelar'>Cancelar</button><button id='guardar'>Guardar ejercicio</button>
    </body>
</html>
