<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8"/>
        <title>Prueba TFG</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <h1>Lista de problemas</h1></br>
    <ul>
        {% for prob in problema %}
        <li> Enunciado general: {{prob.enunciado_general}} Resumen: {{prob.resumen}} 
        </li>
            {% endfor %}
        </ul>
    </body>
</html>
